; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Song 1
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Instrument 1

@samples:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song0ref6:
	.byte $18, $a5, $00, $a5, $18, $a5, $00, $a5, $18, $a5, $00, $a5, $18, $a5, $00, $a5, $47, $ff, $ff, $bf, $47
	.byte $41, $13
	.word @song0ref6
	.byte $47
	.byte $41, $13
	.word @song0ref6
@song0ref34:
	.byte $47, $0c, $a5, $00, $a5, $0c, $a5, $00, $a5, $0c, $a5, $00, $a5, $0c, $a5, $00, $a5, $47, $ff, $ff, $bf
	.byte $41, $13
	.word @song0ref34
	.byte $41, $13
	.word @song0ref34
	.byte $41, $13
	.word @song0ref34
	.byte $41, $13
	.word @song0ref34
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref71:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0c
	.word @song0ref71
	.byte $41, $0c
	.word @song0ref71
	.byte $41, $0c
	.word @song0ref71
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $a9, $80
@song0ref98:
	.byte $24, $a3, $00, $a5, $24, $a5, $00, $a5, $24, $a5, $00, $a5, $24, $a5, $27, $f5, $00, $91, $25, $cd, $00, $e1, $a9
	.byte $41, $0e
	.word @song0ref98
	.byte $33, $f5, $00, $91, $31, $cd, $00, $e1, $a9
	.byte $41, $17
	.word @song0ref98
	.byte $41, $17
	.word @song0ref98
	.byte $41, $0e
	.word @song0ref98
	.byte $33, $f5, $00, $91, $31, $cd, $00, $e1, $a9
	.byte $41, $17
	.word @song0ref98
	.byte $41, $17
	.word @song0ref98
	.byte $41, $16
	.word @song0ref98
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $80
@song0ref171:
	.byte $04, $cd, $00, $cd, $04, $cd, $00, $cd, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $11
	.word @song0ref171
	.byte $41, $11
	.word @song0ref171
	.byte $41, $0b
	.word @song0ref171
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $0c
	.word @song0ref71
	.byte $41, $0c
	.word @song0ref71
	.byte $41, $0c
	.word @song0ref71
	.byte $41, $0c
	.word @song0ref71
	.byte $42
	.word @song0ch4loop
